#!/bin/bash
XP2EXO_EXECUTABLE=/home/pavery/bin/xp2exo

module load intel/intel-13

rm ./visualization/*_steady.exo

$XP2EXO_EXECUTABLE ./mesh/runmesh/fluid_volume.top \
                   ./visualization/uncoupled/fluid_Solution_steady.exo \
                   postpro/uncoupled/Pressure_steady.xpost \
                   postpro/uncoupled/Mach_steady.xpost \
                   postpro/uncoupled/Velocity_steady.xpost \
                   postpro/uncoupled/Displacement_steady.xpost

#/home/pavery/bin/aeros -t structurefile_steady.inp
#$XP2EXO_EXECUTABLE ./structure_volume.top \
                   #./visualization/uncoupled/structure_Solution_steady.exo \
                   #results/uncoupled/strucure_volume_steady.dis \
                   #results/uncoupled/structure_volume_steady.stress.vm


